---
- name: >
    enable : {{ SVC.name }}
    : Enable service
  command:
    cmd: "{{ systemctl }} enable {{ SVC.name }}"
    creates: "{{ systemd_service_dir }}/default.target.wants/{{ SVC.name }}.service"
  become: True
