---
- name: >
    service-file : {{ SVC.name }}
    : Systemd service file
  template:
    src: container.service
    dest: "{{ systemd_service_dir }}/{{ SVC.name }}.service"
    mode: 0640
    owner: "{{ SVC.user }}"
    group: "{{ SVC.user }}"
  become: True
  register: systemd_service_file


- name: >
    service-file : {{ SVC.name }}
    : Systemd daemon reload
  command:
    cmd: "{{ systemctl }} daemon-reload"
  become: True
  when: systemd_service_file.changed


- name: >
    service-file : {{ _user.name }}
    : Enable podman autoupdate timer
  command:
    cmd: "{{ systemctl }} enable --now podman-auto-update.timer"
    creates: "{{ systemd_service_dir }}/timers.target.wants/podman-auto-update.timer"
  become: True
  when: autoupdate
